import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Index(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>ទំព័រ​ដើម</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/siteLogo.png" />
      </Head>

      <main className={styles.main}>
        ត្រូវ​បាន​តភ្ជាប់​ទៅ​មូលដ្ឋាន​ទិន្នន័យ៖ {props.props.isConnected}
      </main>

    </div>
  )
}