//pages/index.py
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home({isConnected}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>ទំព័រ​ដើម</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/siteLogo.png" />
      </Head>

      <main className={styles.main}>
        ត្រូវ​បាន​តភ្ជាប់​ទៅ​មូលដ្ឋាន​ទិន្នន័យ៖ {isConnected}
      </main>

    </div>
  )
}

export async function getServerSideProps(context){
    try{
        const module = await import('../models/setcon.js')
        await module.default
        return{
            props: { isConnected: 'Yes' },
        }
    }catch(e){
        console.error(e)
        return{
            props: { isConnected: 'No' },
        }
    }
}